title: Blog de Sergio
email: sergio@lony.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Blog de Sergio. Hablo un poco de todo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.lony.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lonyelon
show_excerpts: true
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll/scholar
  - jekyll-figure
scholar:
  locale: es
  style: ieee
  bibliography_template: "<p>{{reference}}</p>"
